(diminish 'company-mode)
(diminish 'helm-mode)
(diminish 'projectile-mode)
(diminish 'smartparens-mode)
(diminish 'flycheck-mode)
(diminish 'prelude-mode)
(diminish 'yas-minor-mode)
(diminish 'abbrev-mode)
